# Generated by Django 5.2.8 on 2025-12-13 01:44

import meme_maker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ['-created_at'], 'verbose_name': 'Meme', 'verbose_name_plural': 'Memes'},
        ),
        migrations.AddField(
            model_name='meme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='bottom_text',
            field=models.CharField(blank=True, help_text='Text to display at the bottom of the meme', max_length=200),
        ),
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(help_text='Image file for the meme', upload_to=meme_maker.models.meme_upload_path),
        ),
        migrations.AlterField(
            model_name='meme',
            name='top_text',
            field=models.CharField(blank=True, help_text='Text to display at the top of the meme', max_length=200),
        ),
    ]
