# Generated by Django 5.2.8 on 2025-12-13 02:33

import django.db.models.deletion
import meme_maker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_maker', '0002_alter_meme_options_meme_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The template image', upload_to=meme_maker.models.template_upload_path)),
                ('title', models.CharField(help_text='Searchable title for the template', max_length=200)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags for searching (e.g., 'funny, reaction, cat')", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meme Template',
                'verbose_name_plural': 'Meme Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='meme',
            name='generated_image',
            field=models.ImageField(blank=True, help_text='The final rendered meme image', null=True, upload_to=meme_maker.models.meme_upload_path),
        ),
        migrations.AddField(
            model_name='meme',
            name='text_overlays',
            field=models.JSONField(blank=True, default=dict, help_text='JSON containing text overlay configuration'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='bottom_text',
            field=models.CharField(blank=True, help_text='Legacy: Text at bottom (use text_overlays instead)', max_length=200),
        ),
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, help_text='Legacy: Direct image upload (use template instead)', null=True, upload_to=meme_maker.models.meme_upload_path),
        ),
        migrations.AlterField(
            model_name='meme',
            name='top_text',
            field=models.CharField(blank=True, help_text='Legacy: Text at top (use text_overlays instead)', max_length=200),
        ),
        migrations.AddField(
            model_name='meme',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The template this meme was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memes', to='meme_maker.memetemplate'),
        ),
    ]
