# Generated by Django 5.2.8 on 2025-12-15 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_maker', '0003_memetemplate_meme_generated_image_meme_text_overlays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of ratings received'),
        ),
        migrations.AddField(
            model_name='meme',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0, help_text='Sum of all ratings (for calculating average)'),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of ratings received'),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0, help_text='Sum of all ratings (for calculating average)'),
        ),
        migrations.CreateModel(
            name='MemeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Session key to track who rated', max_length=40)),
                ('stars', models.PositiveSmallIntegerField(help_text='Rating value 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='meme_maker.meme')),
            ],
            options={
                'verbose_name': 'Meme Rating',
                'verbose_name_plural': 'Meme Ratings',
                'unique_together': {('meme', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='TemplateRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Session key to track who rated', max_length=40)),
                ('stars', models.PositiveSmallIntegerField(help_text='Rating value 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='meme_maker.memetemplate')),
            ],
            options={
                'verbose_name': 'Template Rating',
                'verbose_name_plural': 'Template Ratings',
                'unique_together': {('template', 'session_key')},
            },
        ),
    ]
