# Generated by Django 5.2.8 on 2026-01-05 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('meme_maker', '0004_add_rating_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the object being linked to')),
                ('link_type', models.CharField(blank=True, help_text="Optional: categorize the link (e.g., 'created_by', 'featured_in', 'related_to')", max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional: additional data about this link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(help_text='The type of object being linked to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('meme', models.ForeignKey(help_text='The meme being linked', on_delete=django.db.models.deletion.CASCADE, related_name='object_links', to='meme_maker.meme')),
            ],
            options={
                'verbose_name': 'Meme Link',
                'verbose_name_plural': 'Meme Links',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='meme_maker__content_6fa5b9_idx')],
                'unique_together': {('meme', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='TemplateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the object being linked to')),
                ('link_type', models.CharField(blank=True, help_text="Optional: categorize the link (e.g., 'featured', 'owned_by', 'related_to')", max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional: additional data about this link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(help_text='The type of object being linked to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('template', models.ForeignKey(help_text='The template being linked', on_delete=django.db.models.deletion.CASCADE, related_name='object_links', to='meme_maker.memetemplate')),
            ],
            options={
                'verbose_name': 'Template Link',
                'verbose_name_plural': 'Template Links',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='meme_maker__content_651dd2_idx')],
                'unique_together': {('template', 'content_type', 'object_id')},
            },
        ),
    ]
