# Generated by Django 5.2.8 on 2026-01-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_maker', '0008_add_flagging'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='memeflag',
            new_name='meme_maker__created_e695fa_idx',
            old_name='meme_maker_memeflag_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='templateflag',
            new_name='meme_maker__created_2566aa_idx',
            old_name='meme_maker_templateflag_created_at_idx',
        ),
    ]
