# Generated by Django 5.2.8 on 2026-02-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_maker', '0010_external_source_query'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='externalsourcequery',
            new_name='meme_maker__fetched_dbc539_idx',
            old_name='meme_maker__fetched_at_idx',
        ),
    ]
